<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Softcode\Gls\ViewModel\Config $viewModel */
$viewModel = $block->getViewModel();
?>

<script>
    window.softcode = window.softcode || {};

    window.softcode.gls = {
        enabled: <?= /* @noEscape */ $viewModel->isEnabled() ? 'true' : 'false' ?>
    };

    window.softcode.delivery = window.softcode.delivery || {
        mountPoint: '#sc-delivery-methods'
    };
</script>
